f = open('test.txt', 'r')
file_contents = f.read()
words = file_contents.split(' ')
word_count = len(words)
print(word_count)
f.close()

f = open('test.txt', 'r')
file_contents = f.read()
words = file_contents.split(' ')
word_count = len(words)
print(word_count)
f.close()
